export const NEW_BANER_REQUEST = "NEW_BANER_REQUEST";
export const NEW_BANER_SUCCESS = "NEW_BANER_SUCCESS";
export const NEW_BANER_FAIL = "NEW_BANER_FAIL";
export const NEW_BANER_RESET = "NEW_BANER_RESET";

export const DELETE_BANER_REQUEST = "DELETE_BANER_REQUEST";
export const DELETE_BANER_SUCCESS = "DELETE_BANER_SUCCESS";
export const DELETE_BANER_FAIL = "DELETE_BANER_FAIL";
export const DELETE_BANER_RESET = "DELETE_BANER_RESET";

export const ALL_BANER_REQUEST = "ALL_BANER_REQUEST";
export const ALL_BANER_SUCCESS = "ALL_BANER_SUCCESS";
export const ALL_BANER_FAIL = "ALL_BANER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
