export const ALL_CUT_CONSTANT_REQUEST = "ALL_CUT_CONSTANT_REQUEST";
export const ALL_CUT_CONSTANT_SUCCESS = "ALL_CUT_CONSTANT_SUCCESS";
export const ALL_CUT_CONSTANT_FAIL = "ALL_CUT_CONSTANT_FAIL";

export const ADMIN_CUT_CONSTANT_REQUEST = "ADMIN_CUT_CONSTANT_REQUEST";
export const ADMIN_CUT_CONSTANT_SUCCESS = "ADMIN_CUT_CONSTANT_SUCCESS";
export const ADMIN_CUT_CONSTANT_FAIL = "ADMIN_CUT_CONSTANT_FAIL";

export const CREATE_CUT_CONSTANT_REQUEST = "CREATE_CUT_CONSTANT_REQUEST";
export const CREATE_CUT_CONSTANT_SUCCESS = "CREATE_CUT_CONSTANT_SUCCESS";
export const CREATE_CUT_CONSTANT_FAIL = "CREATE_CUT_CONSTANT_FAIL";
export const CREATE_CUT_CONSTANT_RESET = "CREATE_CUT_CONSTANT_RESET";

export const UPDATE_CUT_CONSTANT_REQUEST = "UPDATE_CUT_CONSTANT_REQUEST";
export const UPDATE_CUT_CONSTANT_SUCCESS = "UPDATE_CUT_CONSTANT_SUCCESS";
export const UPDATE_CUT_CONSTANT_FAIL = "UPDATE_CUT_CONSTANT_FAIL";
export const UPDATE_CUT_CONSTANT_RESET = "UPDATE_CUT_CONSTANT_RESET";

export const CUT_DETAILS_CONSTANT_REQUEST = "CUT_DETAILS_CONSTANT_REQUEST";
export const CUT_DETAILS_CONSTANT_SUCCESS = "CUT_DETAILS_CONSTANT_SUCCESS";
export const CUT_DETAILS_CONSTANT_FAIL = "CUT_DETAILS_CONSTANT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
