export const ALL_MODELS_REQUEST = "ALL_MODELS_REQUEST";
export const ALL_MODELS_SUCCESS = "ALL_MODELS_SUCCESS";
export const ALL_MODELS_FAIL = "ALL_MODELS_FAIL";

export const ADMIN_MODELS_REQUEST = "ADMIN_MODELS_REQUEST";
export const ADMIN_MODELS_SUCCESS = "ADMIN_MODELS_SUCCESS";
export const ADMIN_MODELS_FAIL = "ADMIN_MODELS_FAIL";

export const CREATE_MODEL_REQUEST = "CREATE_MODEL_REQUEST";
export const CREATE_MODEL_SUCCESS = "CREATE_MODEL_SUCCESS";
export const CREATE_MODEL_FAIL = "CREATE_MODEL_FAIL";
export const CREATE_MODEL_RESET = "CREATE_MODEL_RESET";

export const UPDATE_MODEL_REQUEST = "UPDATE_MODEL_REQUEST";
export const UPDATE_MODEL_SUCCESS = "UPDATE_MODEL_SUCCESS";
export const UPDATE_MODEL_FAIL = "UPDATE_MODEL_FAIL";
export const UPDATE_MODEL_RESET = "UPDATE_MODEL_RESET";

export const DELETE_MODEL_REQUEST = "DELETE_MODEL_REQUEST";
export const DELETE_MODEL_SUCCESS = "DELETE_MODEL_SUCCESS";
export const DELETE_MODEL_FAIL = "DELETE_MODEL_FAIL";
export const DELETE_MODEL_RESET = "DELETE_MODEL_RESET";

export const MODEL_DETAILS_REQUEST = "MODEL_DETAILS_REQUEST";
export const MODEL_DETAILS_SUCCESS = "MODEL_DETAILS_SUCCESS";
export const MODEL_DETAILS_FAIL = "MODEL_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
