export const ALL_VARIANTS_REQUEST = "ALL_VARIANTS_REQUEST";
export const ALL_VARIANTS_SUCCESS = "ALL_VARIANTS_SUCCESS";
export const ALL_VARIANTS_FAIL = "ALL_VARIANTS_FAIL";

export const ADMIN_VARIANTS_REQUEST = "ADMIN_VARIANTS_REQUEST";
export const ADMIN_VARIANTS_SUCCESS = "ADMIN_VARIANTS_SUCCESS";
export const ADMIN_VARIANTS_FAIL = "ADMIN_VARIANTS_FAIL";

export const CREATE_VARIANT_REQUEST = "CREATE_VARIANT_REQUEST";
export const CREATE_VARIANT_SUCCESS = "CREATE_VARIANT_SUCCESS";
export const CREATE_VARIANT_FAIL = "CREATE_VARIANT_FAIL";
export const CREATE_VARIANT_RESET = "CREATE_VARIANT_RESET";

export const UPDATE_VARIANT_REQUEST = "UPDATE_VARIANT_REQUEST";
export const UPDATE_VARIANT_SUCCESS = "UPDATE_VARIANT_SUCCESS";
export const UPDATE_VARIANT_FAIL = "UPDATE_VARIANT_FAIL";
export const UPDATE_VARIANT_RESET = "UPDATE_VARIANT_RESET";

export const DELETE_VARIANT_REQUEST = "DELETE_VARIANT_REQUEST";
export const DELETE_VARIANT_SUCCESS = "DELETE_VARIANT_SUCCESS";
export const DELETE_VARIANT_FAIL = "DELETE_VARIANT_FAIL";
export const DELETE_VARIANT_RESET = "DELETE_VARIANT_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
